# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package and lock files
COPY package.json pnpm-lock.yaml tsconfig.json .

# Copy source files
COPY index.ts .

# Install dependencies
RUN pnpm install --frozen-lockfile

# Build the project
RUN pnpm run build

# Expose the stdio interface (no port needed)
# Start the MCP server
CMD ["node", "build/index.js"]
